### PR TITLE
jshint improvements 

### PR DESCRIPTION
**Pull request by nightpool**
added a jshintignore, fixed all the errors in chrome and safari bridges, and a good percentage of the errors in the extensions.

### CODE REVIEW

**Comment by nightpool** [comment]
slightly unrelated note: right now, `grunt clean` removes all of the node dev-dependencies. (meaning if you run grunt clean you can't run grunt anymore). this seems unintentional?

also I'm 90% sure all of these changes are correct, but it would be great if someone could test for typos and stuff. (does anyone know how to unit test browser extensions??)

**Comment by hobinjk** [comment]
Thank you so much for this herculean effort!

`grunt clean` should definitely be fixed. I've read through the changes you made and they look reasonable. The only avenue I could see for bugs is if any of the code was relying on JavaScript's implicit coercion or strict equality, but I doubt anyone did that.

In general, I think any errors this could have introduced through typos are either the kind that jshint would catch (imbalanced parenthesis, missing semicolons, etc.) or they are insidious to the point where we probably shouldn't be bothered (relying on the differences between == false, !, and === false).

I'm going to merge, but allow the changes to be uplifted whenever the files change in version. This should limit risk while also giving the development advantages of jshint compliance. It's also the default behavior of the auto-updater.

**Comment by nightpool** [comment]
@hobinjk what's the plan for the gruntfile? I see there's stuff for building and releases in there—should I make sure that works as well?

**Comment by hobinjk** [comment]
Having the Gruntfile capable of building like build.sh would be great. That being said, I've been using build.sh and it hasn't been absolutely terrible so this is not life or death.

**Pull request merged**
