### PR TITLE
Have fun with that manual merge nonsense

### PR DESCRIPTION
**Pull request by dlmarquis**
Some of the updated extensions started referencing variable XKit.api_key, defined (I think) in xkit_patches.js

### CODE REVIEW

**Comment by kyubey-vb** [comment]
Something went wrong. Are you sure there are no merge conflicts?

**Comment by hobinjk** [comment]
nothing to see here, move it along

**Comment by nightpool** [comment]
doesn't gh have a bot tag now?

**Comment by hobinjk** [comment]
@nightpool not that I know of, what do you have in mind?

**Comment by nightpool** [comment]
eh w/e I was just v. confused

**Pull request merged**
